// <auto-generated />
using BitBlog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitBlog.Migrations
{
    [DbContext(typeof(ContentContext))]
    [Migration("20191008072856_blogpost-init")]
    partial class blogpostinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BitBlog.Models.BlogPost", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Title");

                    b.HasKey("Key");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("BitBlog.Models.FrontpageEntry", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<string>("ImageSource");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.HasKey("Key");

                    b.ToTable("FrontpageEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
